#!/usr/bin/env python3
"""
Pairwise latent-trajectory analysis for rebuttal questions about SIRCL.

This script compares two evaluated `run_*` directories at the sample level:
one baseline run and one `+SIRCL` run. It is designed to answer questions like:

1. Does SIRCL help more when the baseline is already correct?
2. When baseline trajectories are wrong, do their geometry statistics look
   different from correct ones?
3. Among baseline-wrong samples, what separates recovered cases from
   still-wrong cases?

Expected input directory structure (generated by `test_multi_dataset.py`):
  run_0/
    predictions.json
    latents.json
    metrics.json
    raw_outputs.json          # optional
    trajectory_stats.json     # optional

Main outputs:
  - sample_level.csv
  - gain_by_baseline_bucket.csv
  - transition_summary.csv
  - geometry_group_summary.csv
  - radius_profiles.csv
  - failure_examples.csv
  - summary.json
  - summary.md
  - several PNG figures under the output directory

Example:
python3 CODI/plots/analyze_sircl_failure_modes.py \
  --baseline-run /path/to/base/gsm8k/run_0 \
  --sircl-run /path/to/sircl/gsm8k/run_0 \
  --output-dir /data/yhao/baseline/CODI/plots/results/sircl_boundary_gsm8k
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import sys
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

import numpy as np

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    plt = None

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from color_config import BAR_EDGE_COLOR, COLOR_LIST, GRID_ALPHA


EPS = 1e-8
DEFAULT_CONFIDENCE_BINS = "0.0,0.25,0.5,0.75,1.01"

GROUP_LABELS = {
    "baseline_correct": "Baseline correct",
    "baseline_wrong": "Baseline wrong",
    "sircl_correct": "+SIRCL correct",
    "sircl_wrong": "+SIRCL wrong",
    "stable_correct": "Both correct",
    "stable_wrong": "Both wrong",
    "recovered": "Recovered by +SIRCL",
    "regressed": "Regressed with +SIRCL",
}

SAMPLE_METRIC_FIELDS = [
    "radius_mean",
    "radius_max",
    "early_radius_mean",
    "late_radius_mean",
    "radius_change",
    "pairwise_diversity_mean",
    "pairwise_diversity_std",
    "path_length",
    "span",
    "effective_movement_ratio",
    "smoothness",
    "dist_to_final_mean",
    "backtracking_rate",
    "violation_rate",
]


@dataclass
class RunBundle:
    label: str
    run_dir: Path
    predictions: List[Any]
    ground_truth: List[Any]
    correct_mask: np.ndarray
    latents: np.ndarray
    raw_outputs: Optional[List[str]]
    metrics: Dict[str, Any]
    trajectory_stats: Dict[str, Any]
    radius_threshold: Optional[float]

    @property
    def accuracy(self) -> float:
        return float(self.correct_mask.mean()) if len(self.correct_mask) else 0.0


@dataclass
class GeometryStats:
    radii: np.ndarray
    sample_metrics: Dict[str, np.ndarray]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze sample-level latent trajectory differences between a baseline run and a +SIRCL run."
    )
    parser.add_argument("--baseline-run", required=True, help="Path to the baseline run_* directory.")
    parser.add_argument("--sircl-run", required=True, help="Path to the +SIRCL run_* directory.")
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Where to save CSV/JSON/PNG outputs. Defaults to CODI/plots/results/<auto_name>.",
    )
    parser.add_argument("--baseline-label", default=None, help="Display label for the baseline run.")
    parser.add_argument("--sircl-label", default=None, help="Display label for the +SIRCL run.")
    parser.add_argument(
        "--baseline-confidence-file",
        default=None,
        help="Optional JSON/CSV file with one confidence score per baseline sample.",
    )
    parser.add_argument(
        "--confidence-bins",
        default=DEFAULT_CONFIDENCE_BINS,
        help="Comma-separated bin edges for optional confidence bucketing.",
    )
    parser.add_argument(
        "--max-samples-per-group",
        type=int,
        default=None,
        help="Optional cap for geometry summaries/plots, useful for quick 100-vs-100 analyses.",
    )
    parser.add_argument(
        "--max-examples-per-transition",
        type=int,
        default=10,
        help="How many failure/recovery examples to save for each transition category.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for any group subsampling.")
    return parser.parse_args()


def safe_name(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", text.strip())
    return cleaned.strip("_") or "analysis"


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def resolve_run_dir(path_str: str) -> Path:
    path = Path(path_str).expanduser().resolve()
    if path.is_dir():
        return path
    if path.is_file():
        if path.name in {
            "predictions.json",
            "latents.json",
            "metrics.json",
            "raw_outputs.json",
            "trajectory_stats.json",
        }:
            return path.parent
    raise FileNotFoundError(f"Could not resolve run directory from: {path_str}")


def load_run_bundle(run_path: str, override_label: Optional[str]) -> RunBundle:
    run_dir = resolve_run_dir(run_path)

    predictions_path = run_dir / "predictions.json"
    latents_path = run_dir / "latents.json"

    if not predictions_path.exists():
        raise FileNotFoundError(f"Missing predictions.json: {predictions_path}")
    if not latents_path.exists():
        raise FileNotFoundError(f"Missing latents.json: {latents_path}")

    predictions_data = load_json(predictions_path)
    latents_data = load_json(latents_path)

    predictions = predictions_data.get("predictions", [])
    ground_truth = predictions_data.get("ground_truth", [])
    if len(predictions) != len(ground_truth):
        raise ValueError(
            f"Prediction/ground-truth length mismatch in {predictions_path}: "
            f"{len(predictions)} vs {len(ground_truth)}"
        )

    latents = np.asarray(latents_data["latents"], dtype=np.float32)
    if latents.shape[0] != len(predictions):
        raise ValueError(
            f"Latent sample count mismatch in {latents_path}: "
            f"{latents.shape[0]} vs {len(predictions)}"
        )

    correct_mask = np.asarray(
        [answers_match(pred, gold) for pred, gold in zip(predictions, ground_truth)],
        dtype=bool,
    )

    metrics = load_json(run_dir / "metrics.json") if (run_dir / "metrics.json").exists() else {}
    trajectory_stats = (
        load_json(run_dir / "trajectory_stats.json") if (run_dir / "trajectory_stats.json").exists() else {}
    )
    raw_outputs = None
    if (run_dir / "raw_outputs.json").exists():
        raw_outputs_data = load_json(run_dir / "raw_outputs.json")
        raw_outputs = raw_outputs_data.get("raw_outputs", [])

    label = override_label or metrics.get("model") or run_dir.parent.parent.name
    radius_threshold = trajectory_stats.get("threshold")
    if radius_threshold is None and metrics.get("trajectory_radius_threshold") is not None:
        radius_threshold = metrics["trajectory_radius_threshold"]

    return RunBundle(
        label=label,
        run_dir=run_dir,
        predictions=predictions,
        ground_truth=ground_truth,
        correct_mask=correct_mask,
        latents=latents,
        raw_outputs=raw_outputs,
        metrics=metrics,
        trajectory_stats=trajectory_stats,
        radius_threshold=float(radius_threshold) if radius_threshold is not None else None,
    )


def _extract_last_boxed_content(text: str) -> Optional[str]:
    matches = re.findall(r"\\boxed\{([^{}]+)\}", text)
    if matches:
        return matches[-1]
    return None


def _unwrap_simple_latex_wrappers(text: str) -> str:
    changed = True
    while changed:
        changed = False
        for pattern in (
            r"^\\text\{(.+)\}$",
            r"^\\mathrm\{(.+)\}$",
            r"^\\operatorname\{(.+)\}$",
        ):
            match = re.fullmatch(pattern, text.strip(), flags=re.DOTALL)
            if match:
                text = match.group(1).strip()
                changed = True
    return text


def _canonicalize_numeric_string(text: str) -> Optional[str]:
    candidate = str(text).strip()
    if not candidate:
        return None

    latex_frac = re.fullmatch(r"\\frac\{(-?\d+)\}\{(-?\d+)\}", candidate)
    slash_frac = re.fullmatch(r"(-?\d+)\s*/\s*(-?\d+)", candidate)
    simple_number = re.fullmatch(r"-?\d+(?:\.\d+)?", candidate)

    try:
        if latex_frac:
            numerator = Decimal(latex_frac.group(1))
            denominator = Decimal(latex_frac.group(2))
            if denominator == 0:
                return None
            value = numerator / denominator
            return format(value.normalize(), "f").rstrip("0").rstrip(".") or "0"
        if slash_frac:
            numerator = Decimal(slash_frac.group(1))
            denominator = Decimal(slash_frac.group(2))
            if denominator == 0:
                return None
            value = numerator / denominator
            return format(value.normalize(), "f").rstrip("0").rstrip(".") or "0"
        if simple_number:
            value = Decimal(candidate)
            return format(value.normalize(), "f").rstrip("0").rstrip(".") or "0"
    except (InvalidOperation, ZeroDivisionError):
        return None
    return None


def normalize_math_answer(text: Any) -> str:
    if text is None:
        return ""

    candidate = str(text).strip()
    boxed = _extract_last_boxed_content(candidate)
    if boxed:
        candidate = boxed.strip()

    candidate = candidate.replace("\\left", "").replace("\\right", "")
    candidate = candidate.replace("\\!", "")
    candidate = candidate.replace("\\,", "")
    candidate = candidate.replace("\\displaystyle", "")
    candidate = candidate.replace("$", "")
    candidate = candidate.replace("\\(", "(").replace("\\)", ")")
    candidate = candidate.replace("\\[", "[").replace("\\]", "]")
    candidate = candidate.replace("^\\circ", "")
    candidate = candidate.replace("^{\\circ}", "")
    candidate = _unwrap_simple_latex_wrappers(candidate)
    candidate = candidate.strip().rstrip(".")

    if candidate.startswith("(") and candidate.endswith(")"):
        inner = candidate[1:-1].strip()
        if "," not in inner:
            candidate = inner

    candidate = re.sub(r"\s+", "", candidate).lower()

    numeric = _canonicalize_numeric_string(candidate)
    if numeric is not None:
        return numeric

    return candidate


def answers_match(pred: Any, gold: Any) -> bool:
    if isinstance(pred, float) and math.isinf(pred):
        return False
    if isinstance(gold, float) and math.isinf(gold):
        return False
    if isinstance(pred, bool) or isinstance(gold, bool):
        return pred == gold
    if isinstance(pred, (int, float)) and isinstance(gold, (int, float)):
        return pred == gold

    pred_norm = normalize_math_answer(pred)
    gold_norm = normalize_math_answer(gold)
    if pred_norm == gold_norm:
        return True

    pred_num = _canonicalize_numeric_string(pred_norm)
    gold_num = _canonicalize_numeric_string(gold_norm)
    return pred_num is not None and pred_num == gold_num


def compute_geometry_stats(latents: np.ndarray, radius_threshold: Optional[float]) -> GeometryStats:
    latents = np.asarray(latents, dtype=np.float32)
    num_samples, num_iters, _ = latents.shape

    centroids = latents.mean(axis=1, keepdims=True)
    radii = np.linalg.norm(latents - centroids, axis=2)

    steps = latents[:, 1:, :] - latents[:, :-1, :]
    step_norms = np.linalg.norm(steps, axis=2) if num_iters > 1 else np.zeros((num_samples, 0), dtype=np.float32)

    path_length = step_norms.sum(axis=1) if step_norms.size else np.zeros(num_samples, dtype=np.float32)
    span = np.linalg.norm(latents[:, -1, :] - latents[:, 0, :], axis=1)
    effective_movement_ratio = np.divide(
        span,
        path_length,
        out=np.ones_like(span, dtype=np.float32),
        where=path_length > EPS,
    )

    if step_norms.shape[1] >= 2:
        step_unit = steps / np.maximum(step_norms[:, :, None], EPS)
        smoothness = np.mean(np.sum(step_unit[:, :-1, :] * step_unit[:, 1:, :], axis=2), axis=1)
    else:
        smoothness = np.zeros(num_samples, dtype=np.float32)

    if num_iters > 1:
        final_token = latents[:, -1:, :]
        dist_to_final = np.linalg.norm(latents[:, :-1, :] - final_token, axis=2)
        dist_to_final_mean = dist_to_final.mean(axis=1)
        if dist_to_final.shape[1] >= 2:
            backtracking_rate = np.mean(dist_to_final[:, 1:] > dist_to_final[:, :-1], axis=1)
        else:
            backtracking_rate = np.zeros(num_samples, dtype=np.float32)
    else:
        dist_to_final_mean = np.zeros(num_samples, dtype=np.float32)
        backtracking_rate = np.zeros(num_samples, dtype=np.float32)

    diversity_tokens = latents[:, :-1, :] if num_iters > 1 else latents
    diversity_token_count = diversity_tokens.shape[1]
    if diversity_token_count >= 2:
        pairwise_sum = np.zeros(num_samples, dtype=np.float64)
        pairwise_sumsq = np.zeros(num_samples, dtype=np.float64)
        pair_count = 0
        for left in range(diversity_token_count):
            for right in range(left + 1, diversity_token_count):
                dist = np.linalg.norm(diversity_tokens[:, right, :] - diversity_tokens[:, left, :], axis=1)
                pairwise_sum += dist
                pairwise_sumsq += dist**2
                pair_count += 1
        pairwise_diversity_mean = (pairwise_sum / pair_count).astype(np.float32)
        pairwise_diversity_std = np.sqrt(
            np.maximum((pairwise_sumsq / pair_count) - pairwise_diversity_mean.astype(np.float64) ** 2, 0.0)
        ).astype(np.float32)
    else:
        pairwise_diversity_mean = np.zeros(num_samples, dtype=np.float32)
        pairwise_diversity_std = np.zeros(num_samples, dtype=np.float32)

    early_end = min(3, num_iters)
    late_start = max(0, num_iters - 3)
    early_radius_mean = radii[:, :early_end].mean(axis=1)
    late_radius_mean = radii[:, late_start:].mean(axis=1)
    radius_change = late_radius_mean - early_radius_mean

    if radius_threshold is not None:
        violation_rate = (radii > radius_threshold).mean(axis=1).astype(np.float32)
    else:
        violation_rate = np.full(num_samples, np.nan, dtype=np.float32)

    sample_metrics = {
        "radius_mean": radii.mean(axis=1).astype(np.float32),
        "radius_max": radii.max(axis=1).astype(np.float32),
        "early_radius_mean": early_radius_mean.astype(np.float32),
        "late_radius_mean": late_radius_mean.astype(np.float32),
        "radius_change": radius_change.astype(np.float32),
        "pairwise_diversity_mean": pairwise_diversity_mean,
        "pairwise_diversity_std": pairwise_diversity_std,
        "path_length": path_length.astype(np.float32),
        "span": span.astype(np.float32),
        "effective_movement_ratio": effective_movement_ratio.astype(np.float32),
        "smoothness": smoothness.astype(np.float32),
        "dist_to_final_mean": dist_to_final_mean.astype(np.float32),
        "backtracking_rate": backtracking_rate.astype(np.float32),
        "violation_rate": violation_rate,
    }

    return GeometryStats(radii=radii.astype(np.float32), sample_metrics=sample_metrics)


def validate_pair(baseline: RunBundle, sircl: RunBundle) -> None:
    if len(baseline.predictions) != len(sircl.predictions):
        raise ValueError(
            f"Sample count mismatch: {len(baseline.predictions)} vs {len(sircl.predictions)}"
        )
    for idx, (base_gold, sircl_gold) in enumerate(zip(baseline.ground_truth, sircl.ground_truth)):
        if normalize_math_answer(base_gold) != normalize_math_answer(sircl_gold):
            raise ValueError(
                f"Ground-truth mismatch at sample {idx}: {base_gold!r} vs {sircl_gold!r}"
            )


def build_group_masks(baseline_correct: np.ndarray, sircl_correct: np.ndarray) -> Dict[str, np.ndarray]:
    return {
        "baseline_correct": baseline_correct,
        "baseline_wrong": ~baseline_correct,
        "sircl_correct": sircl_correct,
        "sircl_wrong": ~sircl_correct,
        "stable_correct": baseline_correct & sircl_correct,
        "stable_wrong": (~baseline_correct) & (~sircl_correct),
        "recovered": (~baseline_correct) & sircl_correct,
        "regressed": baseline_correct & (~sircl_correct),
    }


def maybe_subsample_indices(indices: np.ndarray, max_samples: Optional[int], rng: np.random.Generator) -> np.ndarray:
    if max_samples is None or len(indices) <= max_samples:
        return np.sort(indices)
    return np.sort(rng.choice(indices, size=max_samples, replace=False))


def build_group_indices(
    group_masks: Mapping[str, np.ndarray],
    max_samples_per_group: Optional[int],
    rng: np.random.Generator,
) -> Dict[str, np.ndarray]:
    selected = {}
    for group_name, mask in group_masks.items():
        indices = np.flatnonzero(mask)
        selected[group_name] = maybe_subsample_indices(indices, max_samples_per_group, rng)
    return selected


def summarize_accuracy_by_baseline_bucket(
    baseline_correct: np.ndarray,
    sircl_correct: np.ndarray,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    buckets = {
        "baseline_correct": baseline_correct,
        "baseline_wrong": ~baseline_correct,
        "all": np.ones_like(baseline_correct, dtype=bool),
    }
    for bucket_name, mask in buckets.items():
        count = int(mask.sum())
        if count == 0:
            continue
        base_acc = float(baseline_correct[mask].mean())
        sircl_acc = float(sircl_correct[mask].mean())
        rows.append(
            {
                "bucket": bucket_name,
                "label": GROUP_LABELS.get(bucket_name, bucket_name.title()),
                "count": count,
                "baseline_accuracy": base_acc,
                "sircl_accuracy": sircl_acc,
                "absolute_gain": sircl_acc - base_acc,
                "relative_gain_pct": ((sircl_acc - base_acc) / base_acc * 100.0) if base_acc > EPS else np.nan,
            }
        )
    return rows


def summarize_transitions(group_masks: Mapping[str, np.ndarray], total_samples: int) -> List[Dict[str, Any]]:
    transition_names = ["stable_correct", "recovered", "stable_wrong", "regressed"]
    rows = []
    for name in transition_names:
        count = int(group_masks[name].sum())
        rows.append(
            {
                "transition": name,
                "label": GROUP_LABELS[name],
                "count": count,
                "share": count / total_samples if total_samples else 0.0,
            }
        )
    return rows


def load_confidence_scores(path_str: str, expected_length: int) -> np.ndarray:
    path = Path(path_str).expanduser().resolve()
    suffix = path.suffix.lower()

    if suffix == ".json":
        data = load_json(path)
        if isinstance(data, list):
            if not data:
                raise ValueError(f"Confidence file is empty: {path}")
            if isinstance(data[0], dict):
                values = np.full(expected_length, np.nan, dtype=np.float32)
                for row in data:
                    idx = row.get("sample_idx", row.get("index"))
                    score = row.get("confidence", row.get("score"))
                    if idx is None or score is None:
                        raise ValueError(f"Unsupported confidence row in {path}: {row}")
                    values[int(idx)] = float(score)
                return values
            values = np.asarray(data, dtype=np.float32)
        elif isinstance(data, dict):
            key = None
            for candidate in ("confidence", "confidences", "score", "scores"):
                if candidate in data:
                    key = candidate
                    break
            if key is None:
                raise ValueError(f"Could not find confidence list in JSON: {path}")
            values = np.asarray(data[key], dtype=np.float32)
        else:
            raise ValueError(f"Unsupported confidence JSON format: {path}")
    elif suffix == ".csv":
        values = np.full(expected_length, np.nan, dtype=np.float32)
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        if not rows:
            raise ValueError(f"Confidence CSV is empty: {path}")
        if "confidence" not in rows[0] and "score" not in rows[0]:
            raise ValueError(f"Confidence CSV must contain `confidence` or `score`: {path}")
        score_key = "confidence" if "confidence" in rows[0] else "score"
        index_key = "sample_idx" if "sample_idx" in rows[0] else ("index" if "index" in rows[0] else None)
        if index_key is None:
            ordered = [float(row[score_key]) for row in rows]
            values = np.asarray(ordered, dtype=np.float32)
        else:
            for row in rows:
                values[int(row[index_key])] = float(row[score_key])
    else:
        raise ValueError(f"Unsupported confidence file suffix: {path}")

    if len(values) != expected_length:
        raise ValueError(f"Confidence length mismatch: {len(values)} vs expected {expected_length}")
    return values


def parse_confidence_bins(bin_text: str) -> np.ndarray:
    bins = np.asarray([float(item.strip()) for item in bin_text.split(",") if item.strip()], dtype=np.float32)
    if len(bins) < 2:
        raise ValueError("Need at least two confidence bin edges.")
    if not np.all(np.diff(bins) > 0):
        raise ValueError("Confidence bin edges must be strictly increasing.")
    return bins


def summarize_confidence_buckets(
    confidences: np.ndarray,
    bins: np.ndarray,
    baseline_correct: np.ndarray,
    sircl_correct: np.ndarray,
) -> List[Dict[str, Any]]:
    rows = []
    valid_mask = np.isfinite(confidences)
    for left, right in zip(bins[:-1], bins[1:]):
        mask = valid_mask & (confidences >= left) & (confidences < right)
        count = int(mask.sum())
        if count == 0:
            continue
        base_acc = float(baseline_correct[mask].mean())
        sircl_acc = float(sircl_correct[mask].mean())
        rows.append(
            {
                "bucket": f"[{left:.2f}, {right:.2f})",
                "count": count,
                "baseline_confidence_mean": float(np.mean(confidences[mask])),
                "baseline_accuracy": base_acc,
                "sircl_accuracy": sircl_acc,
                "absolute_gain": sircl_acc - base_acc,
            }
        )
    return rows


def summarize_geometry_groups(
    group_masks: Mapping[str, np.ndarray],
    group_indices: Mapping[str, np.ndarray],
    baseline_geom: GeometryStats,
    sircl_geom: GeometryStats,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for group_name, full_mask in group_masks.items():
        full_count = int(full_mask.sum())
        sampled_indices = group_indices[group_name]
        for source_name, geom in (("baseline", baseline_geom), ("sircl", sircl_geom)):
            row: Dict[str, Any] = {
                "group": group_name,
                "label": GROUP_LABELS[group_name],
                "source": source_name,
                "count": int(len(sampled_indices)),
                "full_count": full_count,
            }
            if len(sampled_indices) == 0:
                for field in SAMPLE_METRIC_FIELDS:
                    row[f"{field}_mean"] = np.nan
                    row[f"{field}_std"] = np.nan
                rows.append(row)
                continue
            for field in SAMPLE_METRIC_FIELDS:
                values = geom.sample_metrics[field][sampled_indices]
                row[f"{field}_mean"] = float(np.mean(values))
                row[f"{field}_std"] = float(np.std(values))
            rows.append(row)
    return rows


def summarize_radius_profiles(
    group_indices: Mapping[str, np.ndarray],
    baseline_geom: GeometryStats,
    sircl_geom: GeometryStats,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for group_name, indices in group_indices.items():
        for source_name, geom in (("baseline", baseline_geom), ("sircl", sircl_geom)):
            if len(indices) == 0:
                continue
            subset = geom.radii[indices]
            for step_idx in range(subset.shape[1]):
                step_values = subset[:, step_idx]
                rows.append(
                    {
                        "group": group_name,
                        "label": GROUP_LABELS[group_name],
                        "source": source_name,
                        "step": step_idx + 1,
                        "count": int(len(indices)),
                        "mean_radius": float(np.mean(step_values)),
                        "std_radius": float(np.std(step_values)),
                        "p25_radius": float(np.percentile(step_values, 25)),
                        "p50_radius": float(np.percentile(step_values, 50)),
                        "p75_radius": float(np.percentile(step_values, 75)),
                    }
                )
    return rows


def build_sample_level_rows(
    baseline: RunBundle,
    sircl: RunBundle,
    baseline_geom: GeometryStats,
    sircl_geom: GeometryStats,
    group_masks: Mapping[str, np.ndarray],
    baseline_confidences: Optional[np.ndarray],
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    num_samples = len(baseline.predictions)
    for idx in range(num_samples):
        transition = (
            "recovered"
            if group_masks["recovered"][idx]
            else "regressed"
            if group_masks["regressed"][idx]
            else "stable_correct"
            if group_masks["stable_correct"][idx]
            else "stable_wrong"
        )
        row: Dict[str, Any] = {
            "sample_idx": idx,
            "gold": baseline.ground_truth[idx],
            "baseline_prediction": baseline.predictions[idx],
            "sircl_prediction": sircl.predictions[idx],
            "baseline_correct": bool(baseline.correct_mask[idx]),
            "sircl_correct": bool(sircl.correct_mask[idx]),
            "gain": int(sircl.correct_mask[idx]) - int(baseline.correct_mask[idx]),
            "transition": transition,
        }
        if baseline_confidences is not None:
            row["baseline_confidence"] = float(baseline_confidences[idx])

        for prefix, geom in (("baseline", baseline_geom), ("sircl", sircl_geom)):
            for field in SAMPLE_METRIC_FIELDS:
                row[f"{prefix}_{field}"] = float(geom.sample_metrics[field][idx])
        rows.append(row)
    return rows


def build_failure_examples(
    baseline: RunBundle,
    sircl: RunBundle,
    baseline_geom: GeometryStats,
    sircl_geom: GeometryStats,
    group_masks: Mapping[str, np.ndarray],
    max_examples_per_transition: int,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    transition_names = ["recovered", "regressed", "stable_wrong"]
    for transition in transition_names:
        indices = np.flatnonzero(group_masks[transition])
        if len(indices) == 0:
            continue
        if transition == "recovered":
            score = baseline_geom.sample_metrics["radius_mean"][indices] - sircl_geom.sample_metrics["radius_mean"][indices]
            order = np.argsort(-score)
        elif transition == "regressed":
            score = sircl_geom.sample_metrics["radius_mean"][indices] - baseline_geom.sample_metrics["radius_mean"][indices]
            order = np.argsort(-score)
        else:
            score = baseline_geom.sample_metrics["radius_mean"][indices]
            order = np.argsort(-score)

        chosen = indices[order[:max_examples_per_transition]]
        for idx in chosen:
            rows.append(
                {
                    "transition": transition,
                    "label": GROUP_LABELS[transition],
                    "sample_idx": int(idx),
                    "gold": baseline.ground_truth[idx],
                    "baseline_prediction": baseline.predictions[idx],
                    "sircl_prediction": sircl.predictions[idx],
                    "baseline_correct": bool(baseline.correct_mask[idx]),
                    "sircl_correct": bool(sircl.correct_mask[idx]),
                    "baseline_radius_mean": float(baseline_geom.sample_metrics["radius_mean"][idx]),
                    "sircl_radius_mean": float(sircl_geom.sample_metrics["radius_mean"][idx]),
                    "baseline_diversity_mean": float(baseline_geom.sample_metrics["pairwise_diversity_mean"][idx]),
                    "sircl_diversity_mean": float(sircl_geom.sample_metrics["pairwise_diversity_mean"][idx]),
                    "baseline_path_length": float(baseline_geom.sample_metrics["path_length"][idx]),
                    "sircl_path_length": float(sircl_geom.sample_metrics["path_length"][idx]),
                    "baseline_raw_output": baseline.raw_outputs[idx] if baseline.raw_outputs else "",
                    "sircl_raw_output": sircl.raw_outputs[idx] if sircl.raw_outputs else "",
                }
            )
    return rows


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def row_lookup(rows: Sequence[Mapping[str, Any]], **filters: Any) -> Optional[Mapping[str, Any]]:
    for row in rows:
        if all(row.get(key) == value for key, value in filters.items()):
            return row
    return None


def plot_accuracy_gain(
    bucket_rows: Sequence[Mapping[str, Any]],
    baseline_label: str,
    sircl_label: str,
    output_path: Path,
) -> None:
    if plt is None:
        return

    plot_rows = [row for row in bucket_rows if row["bucket"] in {"baseline_correct", "baseline_wrong"}]
    if not plot_rows:
        return

    labels = [row["label"] for row in plot_rows]
    baseline_acc = np.asarray([row["baseline_accuracy"] * 100.0 for row in plot_rows], dtype=np.float32)
    sircl_acc = np.asarray([row["sircl_accuracy"] * 100.0 for row in plot_rows], dtype=np.float32)
    deltas = np.asarray([row["absolute_gain"] * 100.0 for row in plot_rows], dtype=np.float32)

    x = np.arange(len(labels))
    width = 0.34

    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(9, 5.5), facecolor="#FFFFFF")
    ax.set_facecolor("#FFFFFF")

    bars1 = ax.bar(
        x - width / 2,
        baseline_acc,
        width=width,
        color=COLOR_LIST[0],
        edgecolor=BAR_EDGE_COLOR,
        linewidth=1.2,
        label=baseline_label,
    )
    bars2 = ax.bar(
        x + width / 2,
        sircl_acc,
        width=width,
        color=COLOR_LIST[1],
        edgecolor=BAR_EDGE_COLOR,
        linewidth=1.2,
        label=sircl_label,
    )

    for bar in list(bars1) + list(bars2):
        height = bar.get_height()
        ax.annotate(
            f"{height:.1f}%",
            xy=(bar.get_x() + bar.get_width() / 2, height),
            xytext=(0, 4),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=10,
        )

    for i, delta in enumerate(deltas):
        y = max(baseline_acc[i], sircl_acc[i]) + 4.5
        ax.text(
            x[i],
            y,
            f"Delta {delta:+.1f}%",
            ha="center",
            va="bottom",
            fontsize=10,
            fontweight="bold",
            color="#333333",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=11)
    ax.set_ylabel("Accuracy (%)", fontsize=12, fontweight="bold")
    ax.set_title("Gain Conditioned On Baseline Correctness", fontsize=13, fontweight="bold")
    ax.yaxis.grid(True, linestyle="--", alpha=GRID_ALPHA)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, fontsize=10)
    plt.tight_layout()
    plt.savefig(output_path, dpi=220, bbox_inches="tight", facecolor="#FFFFFF")
    plt.close(fig)


def plot_radius_profiles_for_groups(
    group_names: Sequence[str],
    group_indices: Mapping[str, np.ndarray],
    radii: np.ndarray,
    title: str,
    output_path: Path,
) -> None:
    if plt is None:
        return

    plotted_groups = [name for name in group_names if len(group_indices.get(name, [])) > 0]
    if not plotted_groups:
        return

    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(8.5, 5.2), facecolor="#FFFFFF")
    ax.set_facecolor("#FFFFFF")
    steps = np.arange(1, radii.shape[1] + 1)

    for color_idx, group_name in enumerate(plotted_groups):
        subset = radii[group_indices[group_name]]
        mean_curve = subset.mean(axis=0)
        p25 = np.percentile(subset, 25, axis=0)
        p75 = np.percentile(subset, 75, axis=0)
        color = COLOR_LIST[color_idx % len(COLOR_LIST)]

        ax.plot(
            steps,
            mean_curve,
            color=color,
            marker="o",
            linewidth=2.2,
            label=f"{GROUP_LABELS[group_name]} (n={len(group_indices[group_name])})",
        )
        ax.fill_between(steps, p25, p75, color=color, alpha=0.18)

    ax.set_xlabel("Latent Step t", fontsize=12, fontweight="bold")
    ax.set_ylabel(r"$r_t$ = distance to trajectory centroid", fontsize=12, fontweight="bold")
    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.yaxis.grid(True, linestyle="--", alpha=GRID_ALPHA)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, fontsize=9)
    plt.tight_layout()
    plt.savefig(output_path, dpi=220, bbox_inches="tight", facecolor="#FFFFFF")
    plt.close(fig)


def plot_diversity_bars(
    group_names: Sequence[str],
    group_indices: Mapping[str, np.ndarray],
    baseline_geom: GeometryStats,
    output_path: Path,
) -> None:
    if plt is None:
        return

    plotted_groups = [name for name in group_names if len(group_indices.get(name, [])) > 0]
    if not plotted_groups:
        return

    values = []
    labels = []
    for group_name in plotted_groups:
        indices = group_indices[group_name]
        values.append(float(np.mean(baseline_geom.sample_metrics["pairwise_diversity_mean"][indices])))
        labels.append(GROUP_LABELS[group_name])

    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(9, 5.2), facecolor="#FFFFFF")
    ax.set_facecolor("#FFFFFF")
    x = np.arange(len(labels))
    bars = ax.bar(
        x,
        values,
        color=[COLOR_LIST[i % len(COLOR_LIST)] for i in range(len(labels))],
        edgecolor=BAR_EDGE_COLOR,
        linewidth=1.2,
        width=0.62,
    )

    for bar in bars:
        height = bar.get_height()
        ax.annotate(
            f"{height:.2f}",
            xy=(bar.get_x() + bar.get_width() / 2, height),
            xytext=(0, 4),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=10,
        )

    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=12, ha="right", fontsize=10)
    ax.set_ylabel("Mean pairwise latent distance", fontsize=12, fontweight="bold")
    ax.set_title("Baseline Token Diversity Across Key Groups", fontsize=13, fontweight="bold")
    ax.yaxis.grid(True, linestyle="--", alpha=GRID_ALPHA)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    plt.savefig(output_path, dpi=220, bbox_inches="tight", facecolor="#FFFFFF")
    plt.close(fig)


def build_summary_payload(
    baseline: RunBundle,
    sircl: RunBundle,
    bucket_rows: Sequence[Mapping[str, Any]],
    transition_rows: Sequence[Mapping[str, Any]],
    confidence_rows: Optional[Sequence[Mapping[str, Any]]],
    group_summary_rows: Sequence[Mapping[str, Any]],
) -> Dict[str, Any]:
    return {
        "baseline": {
            "label": baseline.label,
            "run_dir": str(baseline.run_dir),
            "accuracy": baseline.accuracy,
            "num_samples": len(baseline.predictions),
            "radius_threshold": baseline.radius_threshold,
        },
        "sircl": {
            "label": sircl.label,
            "run_dir": str(sircl.run_dir),
            "accuracy": sircl.accuracy,
            "num_samples": len(sircl.predictions),
            "radius_threshold": sircl.radius_threshold,
        },
        "absolute_gain": sircl.accuracy - baseline.accuracy,
        "relative_gain_pct": ((sircl.accuracy - baseline.accuracy) / baseline.accuracy * 100.0)
        if baseline.accuracy > EPS
        else None,
        "gain_by_baseline_bucket": list(bucket_rows),
        "transition_summary": list(transition_rows),
        "confidence_summary": list(confidence_rows) if confidence_rows is not None else None,
        "geometry_group_summary": list(group_summary_rows),
    }


def build_markdown_summary(
    summary: Mapping[str, Any],
    bucket_rows: Sequence[Mapping[str, Any]],
    transition_rows: Sequence[Mapping[str, Any]],
    group_summary_rows: Sequence[Mapping[str, Any]],
) -> str:
    baseline = summary["baseline"]
    sircl = summary["sircl"]

    base_wrong_row = row_lookup(bucket_rows, bucket="baseline_wrong")
    base_correct_row = row_lookup(bucket_rows, bucket="baseline_correct")
    wrong_base_geom = row_lookup(group_summary_rows, group="baseline_wrong", source="baseline")
    correct_base_geom = row_lookup(group_summary_rows, group="baseline_correct", source="baseline")
    recovered_base_geom = row_lookup(group_summary_rows, group="recovered", source="baseline")
    stable_wrong_base_geom = row_lookup(group_summary_rows, group="stable_wrong", source="baseline")

    lines = [
        "# SIRCL Boundary Analysis",
        "",
        "## Accuracy",
        "",
        f"- Baseline `{baseline['label']}`: {baseline['accuracy'] * 100:.2f}% ({baseline['num_samples']} samples)",
        f"- +SIRCL `{sircl['label']}`: {sircl['accuracy'] * 100:.2f}% ({sircl['num_samples']} samples)",
        f"- Absolute gain: {summary['absolute_gain'] * 100:+.2f}%",
    ]

    if summary["relative_gain_pct"] is not None:
        lines.append(f"- Relative gain: {summary['relative_gain_pct']:+.2f}%")

    lines.extend(
        [
            "",
            "## Gain By Baseline Correctness",
            "",
            "| Bucket | Count | Baseline Acc | +SIRCL Acc | Delta |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
    )
    for row in bucket_rows:
        lines.append(
            f"| {row['label']} | {row['count']} | {row['baseline_accuracy'] * 100:.2f}% | "
            f"{row['sircl_accuracy'] * 100:.2f}% | {row['absolute_gain'] * 100:+.2f}% |"
        )

    lines.extend(
        [
            "",
            "## Transition Counts",
            "",
            "| Transition | Count | Share |",
            "| --- | ---: | ---: |",
        ]
    )
    for row in transition_rows:
        lines.append(f"| {row['label']} | {row['count']} | {row['share'] * 100:.2f}% |")

    lines.extend(["", "## Geometry Highlights (Baseline Trajectories)", ""])

    if base_wrong_row and base_correct_row:
        lines.append(
            f"- Conditioned on baseline correctness, +SIRCL changes accuracy by "
            f"{base_wrong_row['absolute_gain'] * 100:+.2f}% on baseline-wrong samples and "
            f"{base_correct_row['absolute_gain'] * 100:+.2f}% on baseline-correct samples."
        )
    if wrong_base_geom and correct_base_geom:
        lines.append(
            f"- Baseline-wrong trajectories have radius_mean {wrong_base_geom['radius_mean_mean']:.3f} "
            f"vs {correct_base_geom['radius_mean_mean']:.3f} for baseline-correct ones."
        )
        lines.append(
            f"- Baseline-wrong trajectories have token diversity {wrong_base_geom['pairwise_diversity_mean_mean']:.3f} "
            f"vs {correct_base_geom['pairwise_diversity_mean_mean']:.3f} for baseline-correct ones."
        )
    if recovered_base_geom and stable_wrong_base_geom:
        lines.append(
            f"- Among baseline-wrong samples, recovered cases show radius_mean {recovered_base_geom['radius_mean_mean']:.3f} "
            f"vs {stable_wrong_base_geom['radius_mean_mean']:.3f} for still-wrong cases."
        )
        lines.append(
            f"- Among baseline-wrong samples, recovered cases show token diversity "
            f"{recovered_base_geom['pairwise_diversity_mean_mean']:.3f} vs "
            f"{stable_wrong_base_geom['pairwise_diversity_mean_mean']:.3f} for still-wrong cases."
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()

    baseline = load_run_bundle(args.baseline_run, args.baseline_label)
    sircl = load_run_bundle(args.sircl_run, args.sircl_label)
    validate_pair(baseline, sircl)

    auto_output_name = (
        f"sircl_boundary_{safe_name(baseline.label)}_vs_{safe_name(sircl.label)}"
    )
    output_dir = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir
        else (SCRIPT_DIR / "results" / auto_output_name).resolve()
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    baseline_geom = compute_geometry_stats(baseline.latents, baseline.radius_threshold)
    sircl_geom = compute_geometry_stats(sircl.latents, sircl.radius_threshold)

    group_masks = build_group_masks(baseline.correct_mask, sircl.correct_mask)
    rng = np.random.default_rng(args.seed)
    group_indices = build_group_indices(group_masks, args.max_samples_per_group, rng)

    baseline_confidences = None
    confidence_rows = None
    if args.baseline_confidence_file:
        baseline_confidences = load_confidence_scores(
            args.baseline_confidence_file,
            expected_length=len(baseline.predictions),
        )
        bins = parse_confidence_bins(args.confidence_bins)
        confidence_rows = summarize_confidence_buckets(
            baseline_confidences,
            bins,
            baseline.correct_mask,
            sircl.correct_mask,
        )

    bucket_rows = summarize_accuracy_by_baseline_bucket(baseline.correct_mask, sircl.correct_mask)
    transition_rows = summarize_transitions(group_masks, total_samples=len(baseline.predictions))
    group_summary_rows = summarize_geometry_groups(group_masks, group_indices, baseline_geom, sircl_geom)
    radius_profile_rows = summarize_radius_profiles(group_indices, baseline_geom, sircl_geom)
    sample_level_rows = build_sample_level_rows(
        baseline,
        sircl,
        baseline_geom,
        sircl_geom,
        group_masks,
        baseline_confidences,
    )
    failure_example_rows = build_failure_examples(
        baseline,
        sircl,
        baseline_geom,
        sircl_geom,
        group_masks,
        max_examples_per_transition=args.max_examples_per_transition,
    )

    write_csv(output_dir / "sample_level.csv", sample_level_rows)
    write_csv(output_dir / "gain_by_baseline_bucket.csv", bucket_rows)
    write_csv(output_dir / "transition_summary.csv", transition_rows)
    write_csv(output_dir / "geometry_group_summary.csv", group_summary_rows)
    write_csv(output_dir / "radius_profiles.csv", radius_profile_rows)
    write_csv(output_dir / "failure_examples.csv", failure_example_rows)
    if confidence_rows is not None:
        write_csv(output_dir / "gain_by_confidence_bucket.csv", confidence_rows)

    plot_accuracy_gain(
        bucket_rows,
        baseline_label=baseline.label,
        sircl_label=sircl.label,
        output_path=output_dir / "accuracy_gain_by_baseline_bucket.png",
    )
    plot_radius_profiles_for_groups(
        group_names=["baseline_correct", "baseline_wrong"],
        group_indices=group_indices,
        radii=baseline_geom.radii,
        title="Baseline $r_t$ Profile: Correct vs Wrong",
        output_path=output_dir / "baseline_rt_by_correctness.png",
    )
    plot_radius_profiles_for_groups(
        group_names=["recovered", "stable_wrong"],
        group_indices=group_indices,
        radii=baseline_geom.radii,
        title="Baseline-Wrong Samples: Recovered vs Still Wrong",
        output_path=output_dir / "baseline_wrong_rt_split.png",
    )
    plot_diversity_bars(
        group_names=["baseline_correct", "baseline_wrong", "recovered", "stable_wrong"],
        group_indices=group_indices,
        baseline_geom=baseline_geom,
        output_path=output_dir / "baseline_group_diversity.png",
    )

    summary_payload = build_summary_payload(
        baseline=baseline,
        sircl=sircl,
        bucket_rows=bucket_rows,
        transition_rows=transition_rows,
        confidence_rows=confidence_rows,
        group_summary_rows=group_summary_rows,
    )
    with (output_dir / "summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary_payload, f, ensure_ascii=False, indent=2)

    summary_md = build_markdown_summary(
        summary_payload,
        bucket_rows=bucket_rows,
        transition_rows=transition_rows,
        group_summary_rows=group_summary_rows,
    )
    (output_dir / "summary.md").write_text(summary_md, encoding="utf-8")

    print("=" * 80)
    print("SIRCL boundary analysis complete")
    print("=" * 80)
    print(f"Baseline: {baseline.label}")
    print(f"  Accuracy: {baseline.accuracy * 100:.2f}%")
    print(f"  Run dir : {baseline.run_dir}")
    print(f"+SIRCL  : {sircl.label}")
    print(f"  Accuracy: {sircl.accuracy * 100:.2f}%")
    print(f"  Run dir : {sircl.run_dir}")
    print(f"Absolute gain: {(sircl.accuracy - baseline.accuracy) * 100:+.2f}%")
    print(f"Output dir: {output_dir}")


if __name__ == "__main__":
    main()
