# gsm-hard, multi-arith, svamp, gsm8k
uv run test.py \
	--data_name "gsm8k" \
	--output_dir /hpc2hdd/home/yhao481/jhupload/baseline/CODI/outputs/testoutput \
	--model_name_or_path /hpc2hdd/home/yhao481/jhupload/modelscope/LLM-Research/Llama-3.2-1B-Instruct \
	--seed 11 \
	--model_max_length 512 \
	--bf16 \
	--lora_r 128 --lora_alpha 32 --lora_init \
	--batch_size 128 \
	--greedy True \
	--num_latent 6 \
	--use_prj True \
	--prj_dim 2048 \
	--prj_no_ln False \
	--prj_dropout 0.0 \
	--inf_latent_iterations 6 \
	--inf_num_iterations 1 \
	--remove_eos True \
	--use_lora True \
	--ckpt_dir /hpc2hdd/home/yhao481/jhupload/baseline/CODI/outputs/gsm8k_llama1b_latent_decoder-trajectory-euclidean/Llama-3.2-1B-Instruct/ep_10/lr_0.0008/seed_11/checkpoint-29990